# Github action for CICD for photo_duel Azure web application

name: 'Photo Duel CICD'

on:
  push:
    branches: [ "main" ]
  pull_request:

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -var-file="../photo_duel.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file="../photo_duel.tfvars"

    # terraform outputs
    - name: Echo Environment Variables from tf outputs
      run: |
        DB_PASSWORD=$(terraform output -raw db_admin_password)
        echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
    
        DJANGO_SECRET_KEY=$(terraform output -raw django_secret_key)
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" >> $GITHUB_ENV
      
        CR_ADMIN=$(terraform output -raw cr_admin_username)
        echo "CR_ADMIN=$CR_ADMIN" >> $GITHUB_ENV
    
        CR_PASSWORD=$(terraform output -raw cr_admin_password)
        echo "CR_PASSWORD=$CR_PASSWORD" >> $GITHUB_ENV
    
        ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)
        echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
